[app]
name = "Thunderdome"
category = "Games"

[metadata]
author = "dogsbody"
license = "MIT"
url = "https://github.com/dogsbodytech/thunderdome-tildagon"
description = "Control the Thunderdome! Dogsbody's geodesic dome with 5000 LEDs"
version = "2"
